-- Run this SQL script in your Supabase SQL editor to enable private P2P chat
-- This will create the proper database schema for private conversations

-- Update conversations table to support private conversations
ALTER TABLE public.conversations
ADD COLUMN IF NOT EXISTS is_private BOOLEAN DEFAULT false;

-- Create conversation_participants table for access control
CREATE TABLE IF NOT EXISTS public.conversation_participants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ DEFAULT now(),
  last_read_at TIMESTAMPTZ,

  -- Ensure unique user per conversation
  UNIQUE(conversation_id, user_id)
);

-- Add read_at column to messages for read receipts
ALTER TABLE public.messages
ADD COLUMN IF NOT EXISTS read_at TIMESTAMPTZ;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_conversations_private ON public.conversations(is_private, is_active);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_user ON public.conversation_participants(user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_conversation ON public.conversation_participants(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON public.messages(conversation_id, is_deleted);
CREATE INDEX IF NOT EXISTS idx_messages_read_at ON public.messages(read_at);

-- Enable Row Level Security (RLS) for privacy
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- RLS Policies for conversation_participants
CREATE POLICY "Users can view their own conversation participants"
ON public.conversation_participants FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert conversation participants"
ON public.conversation_participants FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- RLS Policies for messages
CREATE POLICY "Users can view messages from their conversations"
ON public.messages FOR SELECT
USING (
  conversation_id IN (
    SELECT conversation_id FROM public.conversation_participants
    WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Users can insert messages to their conversations"
ON public.messages FOR INSERT
WITH CHECK (
  conversation_id IN (
    SELECT conversation_id FROM public.conversation_participants
    WHERE user_id = auth.uid()
  )
);

CREATE POLICY "Users can update their own messages"
ON public.messages FOR UPDATE
USING (sender_id = auth.uid());

-- Grant permissions
GRANT SELECT, INSERT ON public.conversation_participants TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.messages TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.conversations TO authenticated;